### ISSUE TITLE
Plot of Positive correlations in test don't seem to be rendering properly

### ISSUE THREAD

**Issue by ljchang** [neurolearn/neurolearn-web#14]
Negative values are working, but positive values don't seem to be showing up in blue like they should.

http://neuro-learn.org/tests/44

![image](https://cloud.githubusercontent.com/assets/2993338/19216977/4d970f0a-8da0-11e6-9cb8-5cd85fe6732f.png)

**Comment by burnash** [comment]
Fixed. Thanks for spotting this.
