### ISSUE TITLE
Working with large Neurovault metadata

### ISSUE THREAD

**Issue by ljchang** [neurolearn/neurolearn-web#15]
Having some issues working with image metadata for collection 503.  Can't seem to copy more than 1000 rows when select all.

Would be nice to raise limit if there is one imposed by handsontable.

Also, would be nice to download image metadata table as csv file.

**Comment by burnash** [comment]
Were you able to get 1000 rows in the handsontable on the Training Label step? I can see the 100 images limit. It's a bug indeed and I know where it comes from (it's pagination issue, I'm not handling it properly)

I've also noticed a mismatch between the number of images as shown in the search results and the "Selected Images" panel after I hit "select all". 4538 vs 5067 in the search result row.

**Comment by burnash** [comment]
Sorry, I misread the title. Didn't notice NeuroVault at first.

**Comment by burnash** [comment]
It looks like 1000 rows are indeed [a default](http://docs.handsontable.com/0.15.0-beta5/Options.html#copyColsLimit) for maximum rows for copy & paste. I'll raise the value to the number of rows in the HOT. 

>  Also, would be nice to download image metadata table as csv file.

It's also possible. Are you going to use this file for changing images metadata? I'm interested in your workflow for editing this huge collection.

**Comment by ljchang** [comment]
Thanks @burnash.  It's been tricky working with this big dataset.  Uploading has been fine, but getting collection info and images metadata has been slow through the API.  Another thing that might be nice working for large datasets is to be able to see the neurovault image id in the images metadata table.  I think I need to change about 4000 images of this dataset so that they are already resampled and have the metadata attached.  I'm probably just going to delete them and reupload them.

**Comment by burnash** [comment]
Yes, what I think is with collection size like this making changes via UI doesn't make much sence any more.  The API should come to resque. Could you share your code for making changes to this collection (you can email it to me) so I can test why the API is slow. Maybe there's a way to improve pyneurovault_upload or the API to get more performance.

**Comment by burnash** [comment]
Chris has merged and deployed a PR that fixes copy & paste limit: https://github.com/NeuroVault/NeuroVault/pull/578
@ljchang Should I proceed with implementing download as csv for the image metadata table?

**Comment by ljchang** [comment]
Sure, I think that will still be useful for working with big collections

**Comment by ljchang** [comment]
BTW, I was relieved to see that fixing the bug with the pagination results in the model training now results in a sensible weight map.  It correlates about r=.8 with my original results from the paper using different software.

**Comment by burnash** [comment]
Great, I still need to tweak the page size in the pagination (it's 100 images per page now), even though the app now fetches collection data directly from NeuroVault it still takes considerable time to load even for collections with 500-800 images.

**Comment by burnash** [comment]
Fixed in https://github.com/NeuroVault/NeuroVault/pull/579
