### ISSUE TITLE
nltools updated 0.2.6

### ISSUE THREAD

**Issue by ljchang** [neurolearn/neurolearn-web#18]
Hi @burnash, i fixed a bunch of bugs this past week in nltools.  It might be worth updating neurolearn, version 0.2.6 is now on pypi.  I can't remember all of the things I fixed, but here are a couple of important ones for the website.

1) updated cross-validation methods to be compliant with new scikit-learn release.  I think my methods were working okay, but at least one of them seems to have broke with the new scikit-learn update.  One thing to note is that we no longer need to pass an 'n' parameter in the cv_dict.

2) the PCR and LASSOPCR methods had a bug with the intercept, they should now work.

I've also spent quite a bit of time updating the [documentation](http://neurolearn.readthedocs.io/en/latest/index.html).  There are new tutorials showing how to use the basic features.

**Comment by burnash** [comment]
@ljchang very good! I'm switching to PyPI version.

**Comment by burnash** [comment]
Fixed in e7097a7a686f208f4b22894d46a72f6a4f8791b1
