### ISSUE TITLE
Add filter for neurovault data that contains metadata

### ISSUE THREAD

**Issue by ljchang** [neurolearn/neurolearn-web#27]
Would be nice to know which collections have metadata stored that can be used to train models.

Right now only the people who uploaded the data know about this.  I believe this might actually not be exposed to general users on neurovault either.

**Comment by burnash** [comment]
I agree with this. Indeed this data is not exposed to NeuroVault API users, which makes it very hard for Neurolearn users to find images with metadata. I think the best way is to improve the NeuroVault API and to add a field (e.g. "has_metadata".)
