### ISSUE TITLE
Ability to keep model private

### ISSUE THREAD

**Issue by ljchang** [neurolearn/neurolearn-web#6]
It would be great to be able to access private data from neurovault and also have the option to keep a trained model private via the dashboard.

**Comment by burnash** [comment]
These features were implemented some time ago. I forgot to put them into separate PRs so for the reference here are related commits:

* The ability to access private data from NeuroVault: 
  * 443f2cf75e423ec5ca20fd86a75cfa61ab43085f
  * 51b5a74a1fec93bea8b707341ebf6caeca11bb4a

* Settings to keep a trained model private:
  * 89f8186fd1ce5ae0647dfbf81f3b01cdf0cd86d9
  * 8c149d1cecb71ad904aa2716b093a7003c5e0f1d
  * dc64018fc327963a01c46107cd24cec76bb1f271
